[[agents]]
name = "Asistente_Riopaila"

[agents.model]
provider = "ollama"
model = "qwen2.5:1.5b"
temperature = 0.1 # Muy baja para evitar alucinaciones

[agents.capabilities]
tools = [] # VACÍO: Esto desactiva el uso de buscadores externos que causan el error 401
network = []